version: "3.8"

services:
  app:
    build: .
    container_name: multi-language-faq-app
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/faqdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"

volumes:
  mongo-data:
